### ISSUE TITLE
Is there a way to take a github artifact and save it to an issue?

### ISSUE THREAD

**Issue by michaelhofrichter** [actions-ecosystem/action-create-issue#181]
## What you want to add
I'm creating an issue when there is a failure in running a github workflow. The github workflow is saving the errors as an artifact on the workflow:
```
      - name: upload error artifacts
        uses: actions/upload-artifact@v2
        if: ${{ failure() }}
        with:
          name: errors
          path: ./**/error*.jpg
```
There's another step that generates a text report and I'd love to add that text file to the body of the issue. 

Can I get someway to also save that to the issue? 

## Why this is needed

It makes the details in the issue itself more useful. 

Currently I'm creating an issue by saying:
```
      - name: If tests failed create an issue
        if: ${{ failure() }}
        uses: actions-ecosystem/action-create-issue@v1
        with:
          github_token: ${{ secrets.github_token }}
          title: Automated tests failed
          body: |
            An automated test failed. See the action at ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}.
          labels: |
            bug
```
